[package]
name = "vert-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
smallvec = { workspace = true }

[profile.dev]
opt-level = 3
