[workspace]

[package]
name = "arenas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vert-core = { path = "../../" }
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
